set_volume:
  name: Gradually Set Volume
  description: Gradually adjust the volume of media players.
  fields:
    target:
      name: Target
      description: Media players to adjust.
      required: true
      selector:
        target:
          entity:
            domain: media_player
    volume:
      name: Target Volume
      description: The target volume level (0.0 to 1.0).
      required: true
      example: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider
    duration:
      name: Duration
      description: Duration over which to adjust the volume (in seconds).
      required: false
      default: 5
      example: 10
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: seconds
